### ISSUE TITLE
Opening `<host>/login` may result in 500 error (redirect to `null`)

### ISSUE THREAD

**Issue by thlehmann-ionos** [nextcloud/user_oidc#1000]
### Preconditions

* other login methods must be disabled (`./occ config:app:set --value=0 user_oidc allow_multiple_user_backends`)
* only one provider should be configured (`./occ user_oidc:provider` should only display one provider)

### Steps to reproduce

1. Go to the Nextcloud instance **foo**
2. Have your self redirect to the Identity Provider (IdP)
3. Login and let yourself redirect back to Nextcloud
4. Find yourself in Nextcloud
5. Close the browser (do not log out)
6. Open the browser
7. Paste the URL **foo/login** and confirm to open (this might also be a click to a bookmark or pinned history entry)

**Note:** depending on how Nextcloud is run the host **foo** must be suffixed with **/index.php/** (i.e. when running locally on a Dev-Apache) (**https://foo/index.php/bar** vs. **https://foo/bar**).

**Note:** depending on the browser or browser settings mere pasting of the URL or typing may already request the URL before it was submitted. In this case the error would not be reproducible. This behavior could be observed by monitoring network traffic or logs.

### Expected behaviour

You are logged in.

### Actual behaviour

You get redirected to **apps/user_oidc/login/<numeric provider ID, may vary>** and see an internal server error page.

After opening **foo/login** again.

### Server configuration

**Web server:** either Apache or Nginx

**Database:** either SQLite or PostgreSQL

**PHP version:** 8.2

**Nextcloud version:** 30.0.0.14

<details>
<summary>Apps</summary>
```
* cloud_federation_api: 1.13.0
* dav: 1.31.1
* federatedfilesharing: 1.20.0
* files: 2.2.0
* files_reminders: 1.3.0
* files_sharing: 1.22.0
* files_trashbin: 1.20.1
* googleanalytics: 0.0.2
* lookup_server_connector: 1.18.0
* metadata: 0.21.0
* nc_ionos_processes: 1.0.0
* nc_theming: 29.0.0
* oauth2: 1.18.1
* ocs_api_viewer: 1.0.7
* provisioning_api: 1.20.0
* settings: 1.13.0
* sharebymail: 1.20.0
* simplesettings: 1.0.0
* theming: 2.5.0
* twofactor_backupcodes: 1.19.0
* user_oidc: 6.0.1
* viewer: 3.0.0
* webhook_listeners: 1.1.0-dev
* workflowengine: 2.12.0
```
</details>

<details>
<summary>Nextcloud configuration (reduced to user_oidc related instance config and app config)</summary>

```
./occ user_oidc:provider "${ENC_OIDC_CLIENT_ID}" \
	--clientid="${ENC_OIDC_CLIENT_ID}" \
	--clientsecret="${ENC_OIDC_SECRET}" \
	--discoveryuri="${ENC_OIDC_DISCOVERY_URI}" \
	--unique-uid=0 \
	--scope="${ENC_OIDC_SCOPES}"
```

```
<?php
$CONFIG = [
  'user_oidc' => [
	'use_pkce' => true,
	// true and true are the defaults
	// > If the user already exists in another backend, we don't create a
	// > new one in the user_oidc backend. We update the information
	// > (mapped attributes) of the existing user. If the user does not
	// > exist in another backend, we create it in the user_oidc backend
	// https://github.com/nextcloud/user_oidc#soft-auto-provisioning
	'auto_provision' => false,
	// Update *existing information* in Nextcloud backend
	// (false = fail login if existing in other backend)
	'soft_auto_provision' => false,
  ],
];

```
</details>

### Browser

**Browser name:** either Firefox or Chrome

**Browser version:** current version (independent)

**Operating system:** independent

**Browser config:** depending on the browser settings the behavior of pasting or searching URLs in the history may alter the outcome

<details>
<summary>Browser log</summary>

```
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2024-12-03T09:04:59.406Z",
        "id": "page_1",
        "title": "http://localhost:8080/index.php/login",
        "pageTimings": {
          "onContentLoad": 402.6750000048196,
          "onLoad": 405.97999999590684
        }
      }
    ],
    "entries": [
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "connection": "106",
        "pageref": "page_1",
        "request": {
          "method": "GET",
          "url": "http://localhost:8080/index.php/login",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br, zstd"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.9"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Host",
              "value": "localhost:8080"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "document"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "navigate"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "none"
            },
            {
              "name": "Sec-Fetch-User",
              "value": "?1"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
            },
            {
              "name": "sec-ch-ua",
              "value": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "sec-ch-ua-platform",
              "value": "\"Linux\""
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 865,
          "bodySize": 0
        },
        "response": {
          "status": 302,
          "statusText": "Found",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Content-Length",
              "value": "0"
            },
            {
              "name": "Content-Security-Policy",
              "value": "default-src 'self'; script-src 'self' 'nonce-5s4IMfumS6rLzUbMpdgTpDAqWL5qVVF3zaP652U8is0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=UTF-8"
            },
            {
              "name": "Date",
              "value": "Tue, 03 Dec 2024 09:04:59 GMT"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=100"
            },
            {
              "name": "Location",
              "value": "/index.php/apps/user_oidc/login/3"
            },
            {
              "name": "Referrer-Policy",
              "value": "no-referrer"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.52 (Ubuntu)"
            },
            {
              "name": "X-Content-Type-Options",
              "value": "nosniff"
            },
            {
              "name": "X-Frame-Options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "X-Permitted-Cross-Domain-Policies",
              "value": "none"
            },
            {
              "name": "X-Robots-Tag",
              "value": "noindex, nofollow"
            },
            {
              "name": "X-XSS-Protection",
              "value": "1; mode=block"
            }
          ],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "text/html",
            "compression": 0
          },
          "redirectURL": "/index.php/apps/user_oidc/login/3",
          "headersSize": 1183,
          "bodySize": 0,
          "_transferSize": 1183,
          "_error": null,
          "_fetchedViaServiceWorker": false
        },
        "serverIPAddress": "[::1]",
        "startedDateTime": "2024-12-03T09:04:59.370Z",
        "time": 85.8250000019325,
        "timings": {
          "blocked": 36.56599999619834,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0.14100000000000001,
          "wait": 46.98799999769684,
          "receive": 2.130000008037314,
          "_blocked_queueing": 36.26799999619834,
          "_workerStart": -1,
          "_workerReady": -1,
          "_workerFetchStart": -1,
          "_workerRespondWithSettled": -1
        }
      },
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "connection": "106",
        "pageref": "page_1",
        "request": {
          "method": "GET",
          "url": "http://localhost:8080/index.php/apps/user_oidc/login/3",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br, zstd"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.9"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Host",
              "value": "localhost:8080"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "document"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "navigate"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "none"
            },
            {
              "name": "Sec-Fetch-User",
              "value": "?1"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
            },
            {
              "name": "sec-ch-ua",
              "value": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "sec-ch-ua-platform",
              "value": "\"Linux\""
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 1082,
          "bodySize": 0
        },
        "response": {
          "status": 500,
          "statusText": "Internal Server Error",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Connection",
              "value": "close"
            },
            {
              "name": "Content-Length",
              "value": "4138"
            },
            {
              "name": "Content-Security-Policy",
              "value": "default-src 'self'; script-src 'self' 'nonce-pDt2Lrx8o+JcDxzh1IdcNkXjBntvGNa/GUPNlEYqwhw='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=UTF-8"
            },
            {
              "name": "Date",
              "value": "Tue, 03 Dec 2024 09:04:59 GMT"
            },
            {
              "name": "Referrer-Policy",
              "value": "no-referrer"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.52 (Ubuntu)"
            },
            {
              "name": "X-Content-Type-Options",
              "value": "nosniff"
            },
            {
              "name": "X-Frame-Options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "X-Permitted-Cross-Domain-Policies",
              "value": "none"
            },
            {
              "name": "X-Robots-Tag",
              "value": "noindex, nofollow"
            },
            {
              "name": "X-XSS-Protection",
              "value": "1; mode=block"
            }
          ],
          "cookies": [],
          "content": {
            "size": 4138,
            "mimeType": "text/html",
            "compression": 0,
            "text": "<!DOCTYPE html>\n<html class=\"ng-csp\" data-placeholder-focus=\"false\" lang=\"en\" data-locale=\"en\" translate=\"no\" >\n\t<head\n data-requesttoken=\"\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>\n\t\t\tEasyStorage\t\t</title>\n\t\t<meta name=\"csp-nonce\" nonce=\"pDt2Lrx8o+JcDxzh1IdcNkXjBntvGNa/GUPNlEYqwhw=\">\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\n\t\t\t\t<meta name=\"apple-itunes-app\" content=\"app-id=1125420102\">\n\t\t\t\t<meta name=\"theme-color\" content=\"#003D8F\">\n\t\t<link rel=\"icon\" href=\"/index.php/apps/theming/favicon?v=fb9830ef\">\n\t\t<link rel=\"apple-touch-icon\" href=\"/index.php/apps/theming/icon?v=fb9830ef\">\n\t\t<link rel=\"mask-icon\" sizes=\"any\" href=\"/core/img/favicon-mask.svg\" color=\"#003D8F\">\n\t\t<link rel=\"manifest\" href=\"/index.php/apps/theming/manifest?v=fb9830ef\" crossorigin=\"use-credentials\">\n\t\t<link rel=\"stylesheet\" href=\"/core/css/styles.css\">\n<link rel=\"stylesheet\" href=\"/core/css/header.css\">\n<link rel=\"stylesheet\" href=\"/core/css/exception.css\">\n<link rel=\"stylesheet\" href=\"/apps/theming/css/default.css\">\n<link rel=\"stylesheet\" href=\"/core/css/guest.css\">\n\t\t\t\t<script defer src=\"/index.php/apps/googleanalytics/js/tracking\" nonce=\"pDt2Lrx8o+JcDxzh1IdcNkXjBntvGNa/GUPNlEYqwhw=\"></script>\t</head>\n\t<body id=\"body-login\">\n\t\t<noscript>\n\t<div id=\"nojavascript\">\n\t\t<div>\n\t\t\tThis application requires JavaScript for correct operation. Please <a href=\"https://www.enable-javascript.com/\" target=\"_blank\" rel=\"noreferrer noopener\">enable JavaScript</a> and reload the page.\t\t</div>\n\t</div>\n</noscript>\n\t\t<div id=\"initial-state-container\" style=\"display: none;\">\n\t\t\t<input type=\"hidden\" id=\"initial-state-core-versionHash\" value=\"ImFkMDRjMTgyIg==\">\n\t</div>\n\t\t<div class=\"wrapper\">\n\t\t\t<div class=\"v-align\">\n\t\t\t\t\t\t\t\t\t<header>\n\t\t\t\t\t\t<div id=\"header\">\n\t\t\t\t\t\t\t<div class=\"logo\"></div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</header>\n\t\t\t\t\t\t\t\t<main>\n\t\t\t\t\t<h1 class=\"hidden-visually\">\n\t\t\t\t\t\tEasyStorage\t\t\t\t\t</h1>\n\t\t\t\t\t<div class=\"guest-box wide\">\n\t<h2>Internal Server Error</h2>\n\t<p>The server was unable to complete your request.</p>\n\t<p>If this happens again, please send the technical details below to the server administrator.</p>\n\t<p>More details can be found in the server log.</p>\n\t\n\t<h3>Technical details</h3>\n\t<ul>\n\t\t<li>Remote Address: ::1</li>\n\t\t<li>Request ID: NHiYq94yOsTjf41GJtss</li>\n\t\t\t\t\t<li>Type: Exception</li>\n\t\t\t<li>Code: 0</li>\n\t\t\t<li>Message: OCP\\AppFramework\\Http\\RedirectResponse::__construct(): Argument #1 ($redirectURL) must be of type string, null given, called in /var/www/html/apps-external/user_oidc/lib/Controller/LoginController.php on line 213 in file &#039;/var/www/html/lib/public/AppFramework/Http/RedirectResponse.php&#039; line 29</li>\n\t\t\t<li>File: /var/www/html/lib/private/AppFramework/Http/Dispatcher.php</li>\n\t\t\t<li>Line: 146</li>\n\t\t\t</ul>\n\n\t\t\t<br />\n\t\t<h3>Trace</h3>\n\t\t<pre>#0 /var/www/html/lib/private/AppFramework/App.php(161): OC\\AppFramework\\Http\\Dispatcher-&gt;dispatch()\n#1 /var/www/html/lib/private/Route/Router.php(302): OC\\AppFramework\\App::main()\n#2 /var/www/html/lib/base.php(1021): OC\\Route\\Router-&gt;match()\n#3 /var/www/html/index.php(24): OC::handleRequest()\n#4 {main}</pre><br /><h4>Previous</h4><pre>#0 /var/www/html/apps-external/user_oidc/lib/Controller/LoginController.php(213): OCP\\AppFramework\\Http\\RedirectResponse-&gt;__construct()\n#1 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\\UserOIDC\\Controller\\LoginController-&gt;login()\n#2 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\\AppFramework\\Http\\Dispatcher-&gt;executeController()\n#3 /var/www/html/lib/private/AppFramework/App.php(161): OC\\AppFramework\\Http\\Dispatcher-&gt;dispatch()\n#4 /var/www/html/lib/private/Route/Router.php(302): OC\\AppFramework\\App::main()\n#5 /var/www/html/lib/base.php(1021): OC\\Route\\Router-&gt;match()\n#6 /var/www/html/index.php(24): OC::handleRequest()\n#7 {main}</pre>\t</div>\n\t\t\t\t</main>\n\t\t\t</div>\n\t\t</div>\n\t\t\t\t<footer class=\"guest-box \">\n\t\t\t<p class=\"info\">\n\t\t\t\t<a href=\"https://nextcloud.com\" target=\"_blank\" rel=\"noreferrer noopener\" class=\"entity-name\">EasyStorage</a> – a safe home for all your data\t\t\t</p>\n\t\t</footer>\n\t</body>\n</html>\n"
          },
          "redirectURL": "",
          "headersSize": 1152,
          "bodySize": 4138,
          "_transferSize": 5290,
          "_error": null,
          "_fetchedViaServiceWorker": false
        },
        "serverIPAddress": "[::1]",
        "startedDateTime": "2024-12-03T09:04:59.455Z",
        "time": 237.0589999918593,
        "timings": {
          "blocked": 3.4309999902229755,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0.177,
          "wait": 232.43100000557584,
          "receive": 1.0199999960605055,
          "_blocked_queueing": 3.1519999902229756,
          "_workerStart": -1,
          "_workerReady": -1,
          "_workerFetchStart": -1,
          "_workerRespondWithSettled": -1
        }
      }
    ]
  }
}
```
![Image](https://github.com/user-attachments/assets/ec4d893e-0ee7-4579-9f45-15f16d3e1ea1)

</details>

<details>
<summary>Screen cast</summary>

https://github.com/user-attachments/assets/8e405463-bd71-4b43-9df3-7970aba2c5ff

</details>

### Technical infos

`user_oidc/lib/Controller/LoginController.php`:

```
public function login(int $providerId, string $redirectUrl = null) {
	if ($this->userSession->isLoggedIn()) {
		return new RedirectResponse($redirectUrl);
	}

	// ...
}
```

`$redirectUrl` defaults to null here, but may not be `null`, since a `null` destination is not sensible for redirects.

**Comment by thlehmann-ionos** [comment]
Two things are wrong here.

1. The session should be valid actually
2. The redirect should not default to `null` and in case null was passed it should not use it in the redirect

**Comment by janepie** [comment]
Duplicate of #995
